MVCWebApp/Models/Person/Iperson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCWebApp.Models.Person.ViewModel;
namespace MVCWebApp.Models.Person
{
    public interface Iperson
    {
        public List<personproperties> GetAllPersons();
        public personproperties GetPerson(int id);
        public personproperties Add(CreatePersonViewModel createPersonViewModel);
        public bool Delete(int id);
        public List<personproperties> Search(string searchTerm, bool caseSensitive);
        public List<personproperties> Sort(PersonReorderVIewModel sortOptions, string sortType);
    }
}

MVCWebApp/Models/Person/Personpopulate.cs
using MVCWebApp.EFwk;
using MVCWebApp.Models.Person.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCWebApp.Models.City;
namespace MVCWebApp.Models.Person
{
    public class Personpopulate:Iperson
    {
        private readonly personSeedDbContext _context;

        public Personpopulate(personSeedDbContext context)
        {
            _context = context;
        }

        public List<personproperties> GetAllPersons()
        {
            _context.Countries.ToList();
            return _context.People.ToList();
        }

        public personproperties GetPerson(int id)
        {
            return _context.People.Find(id);
        }

        public List<personproperties> Search(string searchTerm, bool caseSensitive)
        {
            List<personproperties> searchList = new List<personproperties>();

            if (searchTerm != null)
            {
                if (caseSensitive)
                {
                    IEnumerable<personproperties> searchList2 = (from Person in _context.People
                                                                 where Person.Name.Contains(searchTerm) || Person.City.CityName.Contains(searchTerm)
                                                                 select Person)
                                                      .ToList();


                    foreach (personproperties item in searchList2)
                    {
                        if (item.Name.Contains(searchTerm) || item.City.CityName.Contains(searchTerm))
                        {
                            searchList.Add(item);
                        }
                    }
                }
                else
                {

                    searchList = _context.People.Where(p => p.City.CityName.Contains(searchTerm) ||
                                                    p.Name.Contains(searchTerm)).ToList();
            }
        }

            return searchList;
        }

        public List<personproperties> Sort(PersonReorderVIewModel sortOptions, string sortType)
        {
            
            List<personproperties> sortedList = _context.People.ToList();

            if (sortType == "city")
            {
                sortedList = _context.People.OrderBy(p => p.City).ToList();
            }
            else if (sortType == "name")
            {
                sortedList = _context.People.OrderBy(p => p.Name).ToList();
            }

            if (sortOptions.ReverseAplhabeticalOrder == true)
            {
                sortedList.Reverse();
            }

            return sortedList;
        }

        public personproperties Add(CreatePersonViewModel createPersonViewModel)
        {
            personproperties person = new personproperties();
            person.Name = createPersonViewModel.Name;
            person.PhoneNumber = createPersonViewModel.PhoneNumber;
            City.City city = _context.Cities.Find(createPersonViewModel.City);
            person.City = city;

            city.People.Add(person);

            _context.Update(city);
            _context.People.Add(person);
            _context.SaveChanges();

            return person;
        }

        public bool Delete(int id)
        {
            if (id > 0)
            {
                var personToDelete = _context.People.Find(id);

                if (personToDelete != null)
                {
                    _context.People.Remove(personToDelete);
                    _context.SaveChanges();
                    return true;
                }
            }
            return false;
        }
    }
}

MVCWebApp/Models/Person/ViewModel/AllPersonViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModel
{
    public class AllPersonViewModel
    {
        public IEnumerable<personproperties> PersonList { get; set; }

        public CreatePersonViewModel CreateViewModel { get; set; }
        //added for the city selecting a single city
        public SelectList CityList { get; set; }


        public string SearchTerm { get; set; }

        public PersonSearchViewModel SearchOptions { get; set; }

        public PersonReorderVIewModel SortOptions { get; set; }
    }
}

MVCWebApp/Models/Person/ViewModel/CreatePersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModel
{
    public class CreatePersonViewModel
    {
        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 2)]
        public string City { get; set; }

        [Required]
        [RegularExpression(@"[\d]+\-?[\d]+",
            ErrorMessage = "Please enter a valid phone number!")]
        [StringLength(15, MinimumLength = 7)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        public CreatePersonViewModel() { }

        public CreatePersonViewModel(string name, string city, string pNumber)
        {
            Name = name;
            City = city;
            PhoneNumber = pNumber;
        }
    }
}

MVCWebApp/Models/Person/ViewModel/PersonReorderVIewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModel
{
    public class PersonReorderVIewModel
    {
        [Display(Name = "Reverse ")]
        public bool ReverseAplhabeticalOrder { get; set; }
    }
}

MVCWebApp/Models/Person/ViewModel/PersonSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModel
{
    public class PersonSearchViewModel
    {
        [Display(Name = "Search Term")]
        public string SearchTerm { get; set; }

        [Display(Name = "Case Sensitive")]
        public bool CaseSensitive { get; set; }
    }
}

MVCWebApp/Models/Person/personproperties.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MVCWebApp.Models;
namespace MVCWebApp.Models.Person
{
    public class personproperties
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public virtual City.City City { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        // languages a person speaks
        public virtual List<PersonLanguage> PersonLanguages { get; set; }
    }
}

MVCWebApp/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models.Person;
using MVCWebApp.Models.Person.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCWebApp.EFwk;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCWebApp.Models;
namespace MVCWebApp.Controllers
{
    public class PersonController : Controller
    {
        private readonly Iperson _personRepository;
        public readonly personSeedDbContext _context;

        public PersonController(personSeedDbContext context, Iperson personRepository)
        {
            _context = context;
            _personRepository = personRepository;
        }

        public IActionResult Index()
        {
            AllPersonViewModel model = new AllPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities.OrderBy(c => c.CityName), "ID", "CityName");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePersonViewModel CreateViewModel)
        {
            if (ModelState.IsValid)
            {

                _personRepository.Add(CreateViewModel);

                return RedirectToAction(nameof(Index));
            }

            AllPersonViewModel model = new AllPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities, "ID", "CityName");

            return View(nameof(Index), model);
        }

        public IActionResult Delete(int id)
        {
            _personRepository.Delete(id);

            AllPersonViewModel model = new AllPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult Search(PersonSearchViewModel searchOptions)
        {

            AllPersonViewModel model = new AllPersonViewModel();
            model.PersonList = _personRepository.Search(searchOptions.SearchTerm, searchOptions.CaseSensitive);
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult SortByCity(PersonReorderVIewModel sortOptions)
        {
            AllPersonViewModel model = new AllPersonViewModel();

            model.PersonList = _personRepository.Sort(sortOptions, "city");
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult SortByName(PersonReorderVIewModel sortOptions)
        {
            AllPersonViewModel model = new AllPersonViewModel();

            model.PersonList = model.PersonList = _personRepository.Sort(sortOptions, "name");
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }
    }
}

MVCWebApp/Views/Person/Index.cshtml
@model MVCWebApp.Models.Person.ViewModel.AllPersonViewModel
@{ ViewData["Title"] = "List of persons"; }
<h1>Person Home</h1>


@{ ViewData["Title"] = "Person List"; }
<h1>PersonIndex</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CreateViewModel.Name" class="control-label"></label>
                <input asp-for="CreateViewModel.Name" class="form-control" />
                <span asp-validation-for="CreateViewModel.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateViewModel.City" class="control-label"></label>
                <select asp-for="CreateViewModel.City" class="form-control" asp-items="Model.CityList"></select>
                <span asp-validation-for="CreateViewModel.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateViewModel.PhoneNumber" class="control-label"></label>
                <input asp-for="CreateViewModel.PhoneNumber" class="form-control" />
                <span asp-validation-for="CreateViewModel.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="create-buttons">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Search" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SearchOptions.SearchTerm" class="control-label"></label>
                <input asp-for="SearchOptions.SearchTerm" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SearchOptions.CaseSensitive" class="control-label"></label>
                <input asp-for="SearchOptions.CaseSensitive" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form method="get">
            <div class="form-group">
                <label asp-for="SortOptions.ReverseAplhabeticalOrder" class="control-label"></label>
                <input asp-for="SortOptions.ReverseAplhabeticalOrder" />
            </div>
            <div class="form-group">
                <input type="submit" value="Sort by City" asp-controller="Person"
                       asp-action="SortByCity" class="btn btn-primary" />
                <input type="submit" value="Sort by Name" asp-controller="Person"
                       asp-action="SortByName" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class=" personlist container">

    <div class="row align-items-start">

        <div class="col">
            <h4>Name</h4>
        </div>

        <div class="col">
            <h4>City</h4>
        </div>

        <div class="col">
            <h4>Phone Number</h4>
        </div>

        <div class="col">
            <h4>Action</h4>
        </div>

    </div>

    @foreach ( MVCWebApp.Models.Person.personproperties item in Model.PersonList)
    {
        <partial name="_partialPersonView" model="item" />
    }

</div>