MVCWebApp/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Controllers
{
    public class DoctorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FeverCheck(string patientTemp)
        {
            if (int.TryParse(patientTemp, out int temp))
            {

                ViewBag.Message = Models.Doctor.CheckFeverInCentigrade.FeverCheck(temp);
            }
            else
            {

                ViewBag.Message = "Enter the temprature in integer value";
            }
            return View("index");
        }
    }
}

MVCWebApp/Controllers/GuessingGameController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCWebApp.Models.GuessingGame;
using MVCWebApp.Models;
using System.Diagnostics;

namespace MVCWebApp.Controllers
{
    public class GuessingGameController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("randomlyGeneratedNumber") == null)
            {
                //generate random number 
                int generatedrn = Models.GuessingGame.comparePlyerRandomNum.GenerateRandomNumber();
                //random number in a session
                HttpContext.Session.SetInt32("randomlyGeneratedNumber", generatedrn);
                //Number of guesses is so far zero
                HttpContext.Session.SetInt32("NumberOfGuesses", 0);
            }
            
            ViewBag.Message = "The secret Number is generated ";
            //if (!HttpContext.Request.Cookies.ContainsKey("LeadingScore"))
            //{
            //    //default highscore = 1000000
            //    SetHighscoreCookie(1000000);
            //}
            return View();
        }
        [HttpPost]
        public IActionResult Index(int EnteredNum)
        {


            if (ModelState.IsValid)
            {
                bool sucess = false;
              
                int generatedrn = Models.GuessingGame.comparePlyerRandomNum.GenerateRandomNumber();
              
                HttpContext.Session.SetInt32("GuessingNumber", EnteredNum);



                sucess = Models.GuessingGame.comparePlyerRandomNum.CheckSucess((int)HttpContext.Session.GetInt32("GuessingNumber"), (int)HttpContext.Session.GetInt32("randomlyGeneratedNumber"));
                //perfect guess
                if (sucess == true)
                {

                    ViewBag.Message = "Congratulations!Your guess was sucessful";
                    //generate random number 
                    generatedrn = Models.GuessingGame.comparePlyerRandomNum.GenerateRandomNumber();
                    //random number in a session
                    HttpContext.Session.SetInt32("randomlyGeneratedNumber", generatedrn);
                    //Number of guesses is so far zero
                    //HttpContext.Session.SetInt32("NumberOfGuesses", 0);
                    //SetHighscoreCookie(tries);
                }

                else
                {
                    HttpContext.Session.SetInt32("GuessingNumber", EnteredNum);
                    ViewBag.Message = Models.GuessingGame.comparePlyerRandomNum.Compare((int)HttpContext.Session.GetInt32("GuessingNumber"), (int)HttpContext.Session.GetInt32("randomlyGeneratedNumber"));
                }

            }
            return View();


        }
        //private void ResetCookieCont()
        //{
        //    CookieOptions cookieOptionReset = new CookieOptions();
        //    cookieOptionReset.Expires = DateTime.Now.AddDays(-1);

        //    //default highscore = 1000000
        //    HttpContext.Response.Cookies.Append("highscore", "1000000", cookieOptionReset);
        //}
        //private void SetHighscoreCookie(int LeadingScore)
        //{
        //    CookieOptions cookieOption = new CookieOptions();
        //    cookieOption.Expires = DateTime.Now.AddDays(1);

        //    HttpContext.Response.Cookies.Append("highscore", LeadingScore.ToString(), cookieOption);
        //}
    }
}

MVCWebApp/Views/Shared/MessageBView.cshtml
@model MessageViewModel

@{ ViewData["Title"] = "Message: " + Model.Message.ToString();}

<p class="h1">@Model.Message</p>    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

MVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width" />

    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/StyleSheet.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <img src="@Url.Content("~/Content/pagelogopic.jpg")" alt="website logo" />
        <ul class="navigation">
            <li class="linavigation">
                @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li class="linavigation">
                @Html.ActionLink("About", "About", "Home")
            </li>
            <li class="linavigation">
                @Html.ActionLink("Contact", "Contact", "Home")
            </li>
            <li class="linavigation">
                @Html.ActionLink("Projects", "Projects", "Home")
            </li>
            <li class="linavigation">
                @Html.ActionLink("Person", "Index", "Person")
            </li>
            <li class="linavigation">
                @Html.ActionLink("Ajax", "Index", "Ajax")
            </li>
                <li class="linavigation">
                @Html.ActionLink("Country", "Index", "Country")
            </li>
            <li class="linavigation">
                @Html.ActionLink("City", "Index", "City")
            </li>
            <li class="linavigation">
                @Html.ActionLink("Language", "Index", "Language")
            </li>

        </ul>

    </header>


    <ul id="TempratureRandom" class="navigationb">
        <li class="linavigationb">
            @Html.ActionLink("check your Temprature", "FeverCheck", "Doctor")
        </li>
        <li Id="hideit" class="linavigationb">
            @Html.ActionLink("Guess new  Random Number", "Index", "GuessingGame", new { @id = "editLink", @class = "button" })


        </li>

    </ul>

  
    <div class="container b">
        @RenderBody()
    </div>
    <footer><p>@DateTime.Now.ToString("dddd, dd MMMM yyyy") - &copy;ABEL HAILE , GÖTEBORG ,2022</p></footer>
</body>
</html>

MVCWebApp/Views/Shared/__partialPerson.cshtml
@model MVCWebApp.Models.Person.personproperties

<div class="row align-items-start">

    <div class="col">
        <p>@Model.Name</p>
    </div>

    <div class="col">
        <p>@Model.City</p>
    </div>

    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>

    <div class="col">
        <a asp-action="Delete" asp-route-id="@Model.ID" class="btn btn-danger">Delete</a>
    </div>
    <div class="col">
        <a asp-action="ShowLanguages" asp-route-id="@Model.ID" class="btn btn-info">Languages</a>
    </div>

</div>

MVCWebApp/Views/Shared/_partialPersonAjax.cshtml
@model MVCWebApp.Models.Person.personproperties

<div class="row align-items-start">

    <div class="col">
        <p>@Model.Name</p>
    </div>

    <div class="col">
        <p>@Model.City</p>
    </div>

    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
     <div class="col">
        <p>@Model.ID</p>
    </div>
  @*  <div class="col">
        <a asp-action="Delete" asp-route-id="@Model.ID" class="btn btn-danger">Delete</a>
    </div>*@

</div>

MVCWebApp/Views/Shared/_partialPersonList.cshtml
@model IEnumerable<MVCWebApp.Models.Person.personproperties>

<div class=" personlist container">

    <div class="row align-items-start">

        <div class="col">
            <h4>Name</h4>
        </div>

        <div class="col">
            <h4>City</h4>
        </div>

        <div class="col">
            <h4>Phone Number</h4>
        </div>

        <div class="col">
            <h4>ID</h4>
        </div>

    </div>

    @foreach (MVCWebApp.Models.Person.personproperties item in Model)
    {
        <partial name="_partialPersonAjax" model="item" />
    }

</div>